# Base image
FROM golang:1.25-alpine AS builder

# Build stage
WORKDIR /app
COPY microservices-demo/src/frontend/ ./frontend/
WORKDIR /app/frontend
# Check if go.mod is inistalled and install if it isn't
RUN if [ ! -f go.mod ]; then go mod init frontend; fi 
# Download dependencies
RUN go mod tidy 
# build go os for linux , build in 64 bit binary and creats a binary file name app
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o app


# runtime stage
FROM alpine:3.19
WORKDIR /app
COPY --from=builder /app/frontend/app .
COPY --from=builder /app/frontend/templates ./templates
ENV PORT 80
EXPOSE 80
CMD [ "./app" ]

