name: Deploy e-commerce Application to ECS 

on:
    push:
        branches: [ "main" ]
        paths-ignore:
            - 'README.md'
            - '**/*.md'
    pull_request:
        branches: [ "main" ]
        paths-ignore:
            - 'README.md'
            - '**/*.md'
            
        

permissions:
    contents: read

jobs:
    deploy:
        name: Deploy to ECS
        runs-on: ubuntu-latest
        environment: production

        env:
            AWS_REGION: ${{ vars.AWS_REGION }}
            ECS_CLUSTER: ${{ vars.ECS_CLUSTER }}
            ECS_SERVICE: ${{ vars.ECS_SERVICE }}
            ECR_REPOSITORY: ${{ vars.ECR_REPOSITORY }}
            CONTAINER_NAME: ${{ vars.CONTAINER_NAME }}
        steps:
            - name: Checkout_repository
              uses: actions/checkout@v4

            - name: Configure_AWS_credentials
              uses: aws-actions/configure-aws-credentials@v1
              with:
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                aws-region: ${{ env.AWS_REGION }}

            - name: Login to ECR
              id: login-ecr
              uses: aws-actions/amazon-ecr-login@v1

            - name: Build, tag, and push image to ECR
              id: build-image
              env:
                ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
                ECR_REPOSITORY: ${{ env.ECR_REPOSITORY }}
                IMAGE_TAG: ${{ github.sha }}

              run: |
                set -euo pipefail

                : ${ECR_REGISTRY:?ECR_REGISTRY is not set}
                : ${ECR_REPOSITORY:?ECR_REPOSITORY is not set}
                : ${IMAGE_TAG:?IMAGE_TAG is not set}

                ECR_REGISTRY=$(echo $ECR_REGISTRY | xargs)
                ECR_REPOSITORY=$(echo $ECR_REPOSITORY | xargs)
                IMAGE_TAG=$(echo $IMAGE_TAG | xargs)

                echo Building docker image...
                docker build -f microservices-demo/src/frontend/Dockerfile -t "$ECR_REGISTRY/$ECR_REPOSITORY:frontend-$IMAGE_TAG" -t "$ECR_REGISTRY/$ECR_REPOSITORY:frontend-latest"  microservices-demo/src/frontend
                docker build -f microservices-demo/src/cartservice/src/Dockerfile -t "$ECR_REGISTRY/$ECR_REPOSITORY:cart-$IMAGE_TAG" -t "$ECR_REGISTRY/$ECR_REPOSITORY:cart-latest" microservices-demo/src/cartservice/src 
                docker build -f microservices-demo/src/checkoutservice/Dockerfile -t "$ECR_REGISTRY/$ECR_REPOSITORY:checkout-$IMAGE_TAG" -t "$ECR_REGISTRY/$ECR_REPOSITORY:checkout-latest" microservices-demo/src/checkoutservice 
                docker build -f microservices-demo/src/currencyservice/Dockerfile -t "$ECR_REGISTRY/$ECR_REPOSITORY:currency-$IMAGE_TAG" -t "$ECR_REGISTRY/$ECR_REPOSITORY:currency-latest" microservices-demo/src/currencyservice
                docker build -f microservices-demo/src/emailservice/Dockerfile -t "$ECR_REGISTRY/$ECR_REPOSITORY:email-$IMAGE_TAG" -t "$ECR_REGISTRY/$ECR_REPOSITORY:email-latest" microservices-demo/src/emailservice
                docker build -f microservices-demo/src/paymentservice/Dockerfile -t "$ECR_REGISTRY/$ECR_REPOSITORY:payment-$IMAGE_TAG" -t "$ECR_REGISTRY/$ECR_REPOSITORY:payment-latest" microservices-demo/src/paymentservice
                docker build -f microservices-demo/src/productcatalogservice/Dockerfile -t "$ECR_REGISTRY/$ECR_REPOSITORY:product-$IMAGE_TAG" -t "$ECR_REGISTRY/$ECR_REPOSITORY:product-latest" microservices-demo/src/productcatalogservice
                docker build -f microservices-demo/src/recommendationservice/Dockerfile -t "$ECR_REGISTRY/$ECR_REPOSITORY:recommendation-$IMAGE_TAG" -t "$ECR_REGISTRY/$ECR_REPOSITORY:recommendation-latest" microservices-demo/src/recommendationservice 
                docker build -f microservices-demo/src/shippingservice/Dockerfile -t "$ECR_REGISTRY/$ECR_REPOSITORY:shipping-$IMAGE_TAG" -t "$ECR_REGISTRY/$ECR_REPOSITORY:shipping-latest" microservices-demo/src/shippingservice
                docker build -f microservices-demo/src/shoppingassistantservice/Dockerfile -t "$ECR_REGISTRY/$ECR_REPOSITORY:shopping-$IMAGE_TAG" -t "$ECR_REGISTRY/$ECR_REPOSITORY:shopping-latest" microservices-demo/src/shoppingassistantservice
        
                echo Pushing docker image to ECR...
                docker push "$ECR_REGISTRY/$ECR_REPOSITORY:frontend-$IMAGE_TAG"
                docker push "$ECR_REGISTRY/$ECR_REPOSITORY:cart-$IMAGE_TAG"
                docker push "$ECR_REGISTRY/$ECR_REPOSITORY:checkout-$IMAGE_TAG"
                docker push "$ECR_REGISTRY/$ECR_REPOSITORY:currency-$IMAGE_TAG"
                docker push "$ECR_REGISTRY/$ECR_REPOSITORY:email-$IMAGE_TAG"
                docker push "$ECR_REGISTRY/$ECR_REPOSITORY:payment-$IMAGE_TAG"
                docker push "$ECR_REGISTRY/$ECR_REPOSITORY:product-$IMAGE_TAG"
                docker push "$ECR_REGISTRY/$ECR_REPOSITORY:recommendation-$IMAGE_TAG"
                docker push "$ECR_REGISTRY/$ECR_REPOSITORY:shipping-$IMAGE_TAG"
                docker push "$ECR_REGISTRY/$ECR_REPOSITORY:shopping-$IMAGE_TAG"

                echo "image=$ECR_REGISTRY/$ECR_REPOSITORY:frontend-$IMAGE_TAG" >> $GITHUB_OUTPUT

            - name: Debug outputs
              run: |
                echo "Container name: ${{ env.CONTAINER_NAME }}"
                echo "Built image: ${{ steps.build-image.outputs.image }}"
                echo "Task definition path: ecs/task-def.json"

            - name: Add image to ECS task definition
              id: task-def
              uses: aws-actions/amazon-ecs-render-task-definition@v1
              with:
                task-definition: ecs/task-def.json
                container-name: ${{ env.CONTAINER_NAME}}
                image: ${{ steps.build-image.outputs.image}}
            
            - name: Debug rendered task definition
              run: |
                echo "Rendered task definition:"
                cat ${{ steps.task-def.outputs.task-definition }}

            - name: Deploy task definition to ECS 
              uses: aws-actions/amazon-ecs-deploy-task-definition@v1
              with:
                task-definition: ${{ steps.task-def.outputs.task-definition }}
                service: ${{ env.ECS_SERVICE }}
                cluster: ${{ env.ECS_CLUSTER }}
                wait-for-service-stability: true


