name: Deploy e-commerce Application to ECS 

on:
    push:
        branches: [ "main" ]
        paths-ignore:
            - 'README.md'
            - '**/*.md'
    pull_request:
        branches: [ "main" ]
        paths-ignore:
            - 'README.md'
            - '**/*.md'
            
        

permissions:
    contents: read

jobs:
    deploy:
        name: Deploy to ECS
        runs-on: ubuntu-latest
        environment: production

        env:
            AWS_REGION: ${{ vars.AWS_REGION }}
            ECS_CLUSTER: ${{ vars.ECS_CLUSTER }}
            ECS_SERVICE: ${{ vars.ECS_SERVICE }}
            ECR_REPOSITORY: ${{ vars.ECR_REPOSITORY }}
            CONTAINER_NAME: ${{ vars.CONTAINER_NAME }}
            GRAFANA_ECS_SERVICE: ${{ vars.GRAFANA_ECS_SERVICE }}
            GRAFANA_CONTAINER: ${{ vars.GRAFANA_CONTAINER   }}
        steps:
            - name: Checkout_repository
              uses: actions/checkout@v4

            - name: Configure_AWS_credentials
              uses: aws-actions/configure-aws-credentials@v1
              with:
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                aws-region: ${{ env.AWS_REGION }}

            - name: Login to ECR
              id: login-ecr
              uses: aws-actions/amazon-ecr-login@v1

            - name: Build, tag, and push image to ECR
              id: build-image
              env:
                ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
                ECR_REPOSITORY: ${{ env.ECR_REPOSITORY }}
                # IMAGE_TAG: ${{ github.sha }}

              run: |
                set -euo pipefail

                : ${ECR_REGISTRY:?ECR_REGISTRY is not set}
                : ${ECR_REPOSITORY:?ECR_REPOSITORY is not set}
                # : ${IMAGE_TAG:?IMAGE_TAG is not set}

                ECR_REGISTRY=$(echo $ECR_REGISTRY | xargs)
                ECR_REPOSITORY=$(echo $ECR_REPOSITORY | xargs)
                # IMAGE_TAG=$(echo $IMAGE_TAG | xargs)

                echo Building microservices images...
                docker build -f microservices-demo/src/frontend/Dockerfile  -t "$ECR_REGISTRY/$ECR_REPOSITORY:frontend-latest"  microservices-demo/src/frontend
                docker build -f microservices-demo/src/cartservice/src/Dockerfile -t "$ECR_REGISTRY/$ECR_REPOSITORY:cart-latest" microservices-demo/src/cartservice/src 
                docker build -f microservices-demo/src/checkoutservice/Dockerfile -t "$ECR_REGISTRY/$ECR_REPOSITORY:checkout-latest" microservices-demo/src/checkoutservice 
                docker build -f microservices-demo/src/currencyservice/Dockerfile -t "$ECR_REGISTRY/$ECR_REPOSITORY:currency-latest" microservices-demo/src/currencyservice
                docker build -f microservices-demo/src/emailservice/Dockerfile  -t "$ECR_REGISTRY/$ECR_REPOSITORY:email-latest" microservices-demo/src/emailservice
                docker build -f microservices-demo/src/paymentservice/Dockerfile -t "$ECR_REGISTRY/$ECR_REPOSITORY:payment-latest" microservices-demo/src/paymentservice
                docker build -f microservices-demo/src/productcatalogservice/Dockerfile -t "$ECR_REGISTRY/$ECR_REPOSITORY:product-latest" microservices-demo/src/productcatalogservice
                docker build -f microservices-demo/src/recommendationservice/Dockerfile -t "$ECR_REGISTRY/$ECR_REPOSITORY:recommendation-latest" microservices-demo/src/recommendationservice 
                docker build -f microservices-demo/src/shippingservice/Dockerfile -t "$ECR_REGISTRY/$ECR_REPOSITORY:shipping-latest" microservices-demo/src/shippingservice
                
                echo Building prometheus image...
                docker build -f prometheus/Dockerfile.prod -t "$ECR_REGISTRY/$ECR_REPOSITORY:prometheus-latest" prometheus
        
                echo Pushing docker all images to ECR...
                docker push "$ECR_REGISTRY/$ECR_REPOSITORY:frontend-latest"
                docker push "$ECR_REGISTRY/$ECR_REPOSITORY:cart-latest"
                docker push "$ECR_REGISTRY/$ECR_REPOSITORY:checkout-latest"
                docker push "$ECR_REGISTRY/$ECR_REPOSITORY:currency-latest"
                docker push "$ECR_REGISTRY/$ECR_REPOSITORY:email-latest"
                docker push "$ECR_REGISTRY/$ECR_REPOSITORY:payment-latest"
                docker push "$ECR_REGISTRY/$ECR_REPOSITORY:product-latest"
                docker push "$ECR_REGISTRY/$ECR_REPOSITORY:recommendation-latest"
                docker push "$ECR_REGISTRY/$ECR_REPOSITORY:shipping-latest"
                docker push "$ECR_REGISTRY/$ECR_REPOSITORY:prometheus-latest"

                echo "All images successfully pushed"

            - name: Register microservices task definition
              id: register-task
              run: |
                echo "Registering new version of task definition"
                TASK_DEF_ARN=$(aws ecs register-task-definition \
                --cli-input-json file://ecs/task-def.json \
                --query 'taskDefinition.taskDefinitionArn' \
                --output text)
                echo "task-def-arn=$TASK_DEF_ARN" >> $GITHUB_OUTPUT
                echo "$TASK_DEF_ARN registered"

            - name: Register grafana task definition
              id: register-grafana-task
              run: |
                echo "Registering new version of grafana task definition"
                TASK_DEF_GRAFANA_ARN=$(aws ecs register-task-definition \
                --cli-input-json file://grafana/ecs/task-def.json \
                --query 'taskDefinition.taskDefinitionArn' \
                --output text)
                echo "task-def-grafana-arn=$TASK_DEF_GRAFANA_ARN" >> $GITHUB_OUTPUT
                echo "$TASK_DEF_GRAFANA_ARN registered"

            - name: Debug rendered task definition
              run: |
                echo "Rendered task definition:"
                cat ${{ steps.register-task.outputs.task-def-arn }}

            - name: Debug rendered grafana task definition
              run: |
                echo "Rendered grafana task definition:"
                cat ${{ steps.register-grafana-task.outputs.task-def-grafana-arn }}

            - name: Deploy task definition to ECS 
              uses: aws-actions/amazon-ecs-deploy-task-definition@v2
              with:
                task-definition: ${{ steps.register-task.outputs.task-def-arn }}
                service: ${{ env.ECS_SERVICE }}
                cluster: ${{ env.ECS_CLUSTER }}
                force-new-deployment: true
                wait-for-service-stability: true

            - name: Deploy task definition to ECS 
              uses: aws-actions/amazon-ecs-deploy-task-definition@v2
              with:
                task-definition: ${{ steps.register-grafana-task.outputs.task-def-grafana-arn }}
                service: ${{ env.GRAFANA_ECS_SERVICE }}
                cluster: ${{ env.ECS_CLUSTER }}
                force-new-deployment: true
                wait-for-service-stability: true


